# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-02 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('permalink', models.CharField(max_length=120, unique=True)),
                ('update_date', models.DateTimeField(verbose_name='Last Updated')),
                ('body_text', models.TextField(blank=True, verbose_name='PageContent')),
            ],
        ),
    ]
